---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nautobot
  labels:
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/component: http-routing
spec:
  gatewayClassName: eg
  listeners:
    - name: nautobot
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nautobot
  labels:
    app.kubernetes.io/name: nautobot
    app.kubernetes.io/component: http-routing
spec:
  parentRefs:
    - name: nautobot
  hostnames:
    - nautobot.breeze-blocks.net
  rules:
    - backendRefs:
        - name: nautobot
          port: 80
