---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nautobot
spec:
  provider: vault
  secretObjects:
    - data:
        - key: password
          objectName: nautobot-password
        - key: username
          objectName: nautobot-username
        - key: host
          objectName: nautobot-host
        - key: engine
          objectName: nautobot-engine
        - key: port
          objectName: nautobot-port
        - key: timeout
          objectName: nautobot-timeout
        - key: db
          objectName: nautobot-db
        - key: database
        - objectName: nautobot-database
      secretName: nautobot-postgres
      type: Opaque
  parameters:
    roleName: "nautobot"
    vaultAddress: "http://vault.breeze-blocks.net"
    objects: |
      - objectName: "nautobot-password"
        secretPath: "internal/database/nautobot"
        secretKey: "password"
      - objectName: "nautobot-username"
        secretPath: "internal/database/nautobot"
        secretKey: "username"
      - objectName: "nautobot-host"
        secretPath: "internal/database/nautobot"
        secretKey: "host"
      - objectName: "nautobot-port"
        secretPath: "internal/database/nautobot"
        secretKey: "port"
      - objectName: "nautobot-timeout"
        secretPath: "internal/database/nautobot"
        secretKey: "timeout"
      - objectName: "nautobot-engine"
        secretPath: "internal/database/nautobot"
        secretKey: "engine"
      - objectName: "nautobot-db"
        secretPath: "internal/database/nautobot"
        secretKey: "db"
      - objectName: "nautobot-database"
        secretPath: "internal/database/nautobot"
        secretKey: "database"
