---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nautobot
  annotations:
    vault.hashicorp.com/tls-skip-verify: "true"
spec:
  provider: vault
  secretObjects:
    - data:
        - key: password
          objectName: nautobot-password
        - key: engine
          objectName: nautobot-engine
        - key: host
          objectName: nautobot-host
        - key: database
          objectName: nautobot-database
        - key: db
          objectName: nautobot-db
        - key: username
          objectName: nautobot-username
        - key: port
          objectName: nautobot-port
      secretName: nautobot-postgres
      type: Opaque
  parameters:
    roleName: "nautobot"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "nautobot-password"
        secretPath: "internal/data/database/nautobot"
        secretKey: "password"
      - objectName: "nautobot-engine"
        secretPath: "internal/data/database/nautobot"
        secretKey: "engine"
      - objectName: "nautobot-host"
        secretPath: "internal/data/database/nautobot"
        secretKey: "host"
      - objectName: "nautobot-database"
        secretPath: "internal/data/database/nautobot"
        secretKey: "database"
      - objectName: "nautobot-db"
        secretPath: "internal/data/database/nautobot"
        secretKey: "db"
      - objectName: "nautobot-username"
        secretPath: "internal/data/database/nautobot"
        secretKey: "username"
      - objectName: "nautobot-port"
        secretPath: "internal/data/database/nautobot"
        secretName: "port"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nautobot-su
  annotations:
    vault.hashicorp.com/tls-skip-verify: "true"
spec:
  provider: vault
  secretObjects:
    - data:
        - key: password
          objectName: su-password
        - key: secretKey
          objectName: su-secretKey
        - key: token
          objectName: su-token
        - key: email
          objectName: su-email
        - key: username
          objectName: su-username
      secretName: nautobot-superuser
      type: Opaque
  parameters:
    roleName: "nautobot"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "su-password"
        secretPath: "internal/data/nautobot/superuser"
        secretKey: "password"
      - objectName: "su-secretKey"
        secretPath: "internal/data/nautobot/superuser"
        secretKey: "secretKey"
      - objectName: "su-token"
        secretPath: "internal/data/nautobot/superuser"
        secretKey: "token"
      - objectName: "su-email"
        secretPath: "internal/data/nautobot/superuser"
        secretKey: "email"
      - objectName: "su-username"
        secretPath: "internal/data/nautobot/superuser"
        secretKey: "username"
