apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-nautobot
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: nautobot-database-password
    - key: username
      objectName: nautobot-database-username
    - key: port
      objectName: nautobot-database-port
    - key: timeout
      objectName: nautobot-database-timeout
    - key: engine
      objectName: nautobot-database-engine
    - key: database
      objectName: nautobot-database-database
    secretName: nautobot-postgres
    type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "nautobot-password-port"
        secretPath: "internal/data/database/nautobot"
        secretKey: "port"
      - objectName: "nautobot-database-password"
        secretPath: "internal/data/database/nautobot
        secretKey: "password"
      - objectName: "nautobot-database-username"
        secretPath: "internal/data/database/nautobot
        secretKey: "username"
      - objectName: "nautobot-database-engine"
        secretPath: "internal/data/database/nautobot
        secretKey: "engine"
      - objectName: "nautobot-database-timeout"
        secretPath: "internal/data/database/nautobot
        secretKey: "timeout"
      - objectName: "nautobot-database-database"
        secretPath: "internal/data/database/nautobot
        secretKey: "database"
