{{- if eq .Values.type "StatefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernets.io/name: {{ .Chart.Name }}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ include "nautobot.name" . }}
      labels:
        app.kubernetes.io/name: {{ include "nautobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          command: [ "/opt/nautobot/bin/nautobot-server"]
          args: ["--config-path","/opt/nautobot/.nautobot/nautobot_config.py", "runserver", "0.0.0.0:8000"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: {{ .Release.Name }}
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: {{ .Values.config.worker.broker }}
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: port
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.db.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: host
            - name: NAUTOBOT_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: port
            - name: NAUTOBOT_REDIS_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: scheme
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: email
            - name: NAUTOBOT_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: username
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
            - name: nautobot-resolv
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
        - name: scheduler
          image: "{{ .Values.config.worker.img.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5672
              name: scheduler
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: port
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.db.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: host
            - name: NAUTOBOT_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: port
            - name: NAUTOBOT_REDIS_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: scheme
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: email
            - name: NAUTOBOT_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: username
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-resolv
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
        - name: worker
          image: "{{ .Values.config.worker.img.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5673
              name: worker
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: database
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.db.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: host
            - name: NAUTOBOT_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis
                  key: port
            - name: NAUTOBOT_REDIS_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: scheme
                  name: nautobot-redis
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: email
            - name: NAUTOBOT_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: username
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-superuser
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-resolv
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
      imagePullSecrets:
        - name: ghcr
      securityContext:
        fsGroup: 1000
      volumes:
        - name: nautobot-resolv
          configMap:
            name: nautobot-resolv
        - name: nautobot-config
          configMap:
            name: nautobot-config
            items:
              - key: .bashrc
                path: .bashrc
              - key: uwsgi.ini
                path: uwsgi.ini
              - key: nautobot_config.py
                path: nautobot_config.py
  volumeClaimTemplates:
    - metadata:
        name: nautobot
      spec:
        accessModes:
          - ReadWriteMany
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
        volumeMode: Filesystem
{{ end }}
