{{- if eq .Values.type "StatefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.nameOverride }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernets.io/name: {{ .Values.nameOverride }}
  name: {{ .Values.fullnameOverride }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nautobot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Values.nameOverride }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ include "nautobot.name" . }}
      labels:
        app.kubernetes.io/name: {{ include "nautobot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: nautobot
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: {{ .Values.config.worker.broker }}
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: name
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              value: {{ .Values.config.worker.host }}
            - name: NAUTOBOT_REDIS_PORT
              value: "6379"
            - name: NAUTOBOT_REDIS_SCHEME
              value: redis
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_NAME
              value: {{ .Values.superUser.name }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: nautobot
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
        - name: worker
          command:
            - /bin/bash
            - -c
            - 'while true; do sleep 3600; done'
            # - bin/nautobot-server
            # - celery
            # - --config
            # - .nautobot/nautobot_config.py
            # - worker
          image: "{{ .Values.config.worker.img.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9700
              name: worker
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: name
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis-config
                  key: host
            - name: NAUTOBOT_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis-config
                  key: port
            - name: NAUTOBOT_REDIS_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: scheme
                  name: nautobot-redis-config
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_NAME
              value: {{ .Values.superUser.name }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: {{ .Values.persistence.name }}
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-resolv
              mountPath: /etc/resolv.conf
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
        - name: scheduler
          command:
            - /bin/bash
            - -c
            - 'while true; do sleep 3600; done'
            # - bin/nautobot-server
            # - celery
            # - --config
            # - .nautobot/nautobot_config.py
            # - beat
            # - --loglevel
            # - DEBUG
          image: "{{ .Values.config.worker.img.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7890
              name: scheduler
          env:
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: {{ .Values.config.allowed_hosts | quote }}
            - name: NAUTOBOT_CACHES_BACKEND
              value: {{ .Values.config.caches_backend }}
            - name: NAUTOBOT_CELERY_BROKER_URL
              value: "redis://redis.database.svc.cluster.local:6379/0"
            - name: NAUTOBOT_CELERY_RESULT_BACKEND
              value: {{ .Values.config.worker.results }}
            - name: NAUTOBOT_CREATE_SUPERUSER
              value: {{ .Values.superUser.create | quote }}
            - name: NAUTOBOT_CORS_ALLOW_ALL_ORIGINS
              value: 'True'
            - name: NAUTOBOT_CELERY_TASK_DEFAULT_QUEUE
              value: 'default-celery'
            - name: NAUTOBOT_DEBUG
              value: 'True'
            - name: NAUTOBOT_DB_ENGINE
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: engine
            - name: NAUTOBOT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: name
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: password
            - name: NAUTOBOT_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: host
            - name: NAUTOBOT_DB_TIMEOUT
              value: {{ .Values.database.timeout | quote }}
            - name: NAUTOBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nautobot-postgres
                  key: username
            - name: NAUTOBOT_ROOT
              value: /opt/nautobot
            - name: NAUTOBOT_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis-config
                  key: host
            - name: NAUTOBOT_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis-config
                  key: port
            - name: NAUTOBOT_REDIS_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: nautobot-redis-config
                  key: scheme
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: secretKey
            - name: NAUTOBOT_SUPERUSER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: token
            - name: NAUTOBOT_SUPERUSER_EMAIL
              value: {{ .Values.superUser.email }}
            - name: NAUTOBOT_SUPERUSER_NAME
              value: {{ .Values.superUser.name }}
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.superUser.secret.name }}
                  key: password
            - name: NAUTOBOT_TIME_ZONE
              value: 'America/Los_Angeles'
          volumeMounts:
            - name: {{ .Values.persistence.name }}
              mountPath: /opt/
              subPath: nautobot
            - name: nautobot-resolv
              mountPath: /etc/resolv.conf
            - name: nautobot-config
              mountPath: /opt/nautobot/.nautobot
      imagePullSecrets:
        - name: ghcr
      securityContext:
        fsGroup: 1000
      volumes:
        - name: nautobot-resolv
          configMap:
            name: nautobot-resolv
        - name: nautobot-config
          configMap:
            name: nautobot-config
            items:
              - key: .bashrc
                path: .bashrc
              - key: uwsgi.ini
                path: uwsgi.ini
              - key: nautobot_config.py
                path: nautobot_config.py
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.persistence.name }}
      spec:
        accessModes:
          - ReadWriteMany
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
        volumeMode: Filesystem
{{ end }}
