---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: http-routing
  annotations:
    cert-manager.io/cluster-issuer: comms-svc-int
    cert-manager.io/common-name: {{ .Release.Name }}.breeze-blocks.net
    cert-manager.io/usages: key agreement,digital signature, server auth
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: {{ .Release.Name }}.breeze-blocks.net
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Release.Name }}.breeze-blocks.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: "{{ .Release.Name }}-tls"
            kind: Secret
            group: ""
