---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Release.Name }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Release.Name }}
      port: 3000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
    # timeouts:
    #   request: "2s"
  hostnames:
    - loki.breeze-blocks.net
    - loki.monitoring.svc.cluster.local
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}
          port: 80
