- job_name: systemd-exporter
  honor_labels: true
  relabel_configs:
    - action: labelkeep
      regex: (.+)
    - source_labels:
        - "__address__"
      action: replace
      regex: ([a-z0-9]+).+
      target_label: node
      replacement: $1
    - action: replace
      regex: ([a-z0-9]+)\.([a-z0-9\-\.]+).*
      replacement: $1.$2
      source_labels:
        - "__address__"
      target_label: hostname
  scrape_interval: 29s
  scrape_timeout: 5s
  static_configs:
    - targets:
        - backup.breeze-blocks.net:9558
        - cms00.breeze-blocks.net:9558
        - cms01.breeze-blocks.net:9558
        - cms02.breeze-blocks.net:9558
        - cms03.breeze-blocks.net:9558
        - cms04.breeze-blocks.net:9558
        - cms05.breeze-blocks.net:9558
        - marius.breeze-blocks.net:9558
        - media.breeze-blocks.net:9558
        - ns01.breeze-blocks.net:9091
        - ns03.breeze-blocks.net:9091
        - ns04.breeze-blocks.net:9091
        - ostium.breeze-blocks.net:9091
        - sulla-felix.breeze-blocks.net:9558
        - thw00.breeze-blocks.net:9558
        - thw01.breeze-blocks.net:9558
        - thw02.breeze-blocks.net:9558
        - thw03.breeze-blocks.net:9558
        - thw04.breeze-blocks.net:9558
        - thw05.breeze-blocks.net:9558
        - whac.breeze-blocks.net:9558
