---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ .Release.Name }}-tls-redirect"
spec:
  parentRefs:
    - name: "{{ .Release.Name }}"
      sectionName: http
  hostnames:
    - {{ .Values.server.service.hostname }}
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ .Release.Name }}"
spec:
  parentRefs:
    - name: "{{ .Release.Name }}"
      sectionName: https
  hostnames:
    - {{ .Values.server.service.hostname }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      backendRefs:
        - name: {{ .Release.Name }}
          port: {{ .Values.server.service.servicePort }}
          weight: 1
