apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.server.service.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.server.service.servicePort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: {{ .Values.server.service.type }}
