{
 "title": "glances",
 "description": "Some output from the glances prometheus exporter.",
 "tags": [
  "glances",
  "simple"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(glances_load_min1,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Glances $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory Usage by percentage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "glances_mem_total{hostname=\"$hostname\"}",
     "legendFormat": "total $hostname"
    },
    {
     "expr": "glances_mem_used{hostname=\"$hostname\"}",
     "legendFormat": "used $hostname"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glances_processcount_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glances_core_phys{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk i/o",
   "type": "timeseries",
   "description": "Read vs write/s",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "glances_diskio_write_count_rate_per_sec{hostname=\"$hostname\"}",
     "legendFormat": "$hostname {{disk_name}} write/s"
    },
    {
     "expr": "glances_diskio_read_count_rate_per_sec{hostname=\"$hostname\"}*-1",
     "legendFormat": "$hostname {{disk_name}} read/s"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "CPU Load",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "glances_load_min1{hostname=\"$hostname\"}",
     "legendFormat": "load 1 $hostname"
    },
    {
     "expr": "glances_load_min5{hostname=\"$hostname\"}",
     "legendFormat": "load 5 $hostname"
    },
    {
     "expr": "glances_load_min15{hostname=\"$hostname\"}",
     "legendFormat": "load 15 $hostname"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "CPU Usage by Percentage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_cpu_user{hostname=\"$hostname\"}",
     "legendFormat": "CPU Total $hostname"
    },
    {
     "expr": "glances_cpu_system{hostname=\"$hostname\"}",
     "legendFormat": "CPU System $hostname"
    },
    {
     "expr": "glances_cpu_iowait{hostname=\"$hostname\"}",
     "legendFormat": "CPU IOWait $hostname"
    }
   ]
  },
  {
   "title": "$hostname net interface",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "glances_network_bytes_all_rate_per_sec{hostname=\"$hostname\"}",
     "legendFormat": "network rx $hostname {{ interface_name }}"
    },
    {
     "expr": "glances_network_bytes_recv_rate_per_sec{hostname=\"$hostname\"}*-1",
     "legendFormat": "network tx $hostname {{ interface_name }}"
    }
   ]
  }
 ]
}