{
 "title": "glances",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(glances_load_min1,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glances_core_phys{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory Usage by percentage",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "glances_mem_total{hostname=\"$hostname\"}",
     "legendFormat": "total $hostname"
    },
    {
     "expr": "glances_mem_used{hostname=\"$hostname\"}",
     "legendFormat": "used $hostname"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glances_processcount_total{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "CPU Usage by Percentage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_cpu_user{hostname=\"$hostname\"}",
     "legendFormat": "CPU Total $hostname"
    },
    {
     "expr": "glances_cpu_system{hostname=\"$hostname\"}",
     "legendFormat": "CPU System $hostname"
    },
    {
     "expr": "glances_cpu_iowait{hostname=\"$hostname\"}",
     "legendFormat": "CPU IOWait $hostname"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "CPU Load",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "glances_load_min1{hostname=\"$hostname\"}",
     "legendFormat": "load 1 $hostname"
    },
    {
     "expr": "glances_load_min5{hostname=\"$hostname\"}",
     "legendFormat": "load 5 $hostname"
    },
    {
     "expr": "glances_load_min15{hostname=\"$hostname\"}",
     "legendFormat": "load 15 $hostname"
    }
   ]
  },
  {
   "title": "eno1 net interface",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "glances_network_bytes_all_rate_per_sec{hostname=\"$hostname\", interface_name=\"eno1\"}",
     "legendFormat": "network rx $hostname eno1"
    },
    {
     "expr": "glances_network_bytes_recv_rate_per_sec{hostname=\"$hostname\", interface_name=\"eno1\"}*-1",
     "legendFormat": "network tx cms02 eno1"
    }
   ]
  }
 ]
}