{
 "title": "qBittorrent",
 "description": "A comprehensive Grafana dashboard to visualize qBittorrent activity and performance metrics — including global download/upload speeds, torrent states, connection status, peer ratios, and tracker statistics. Perfect for real-time torrent monitoring.",
 "tags": [ "torrent" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Global Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_upload_speed_bytes"
    }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(qbittorrent_transfer_connection_status) by (connection_status)"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max(qbittorrent_transfer_connection_status) by (connection_status)"
    }
   ]
  },
  {
   "title": "qBittorrent Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "qbittorrent_app_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes/qbittorrent_global_alltime_downloaded_bytes"
    }
   ]
  },
  {
   "title": "Session Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_session_uploaded_bytes"
    }
   ]
  },
  {
   "title": "Session Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_session_downloaded_bytes"
    }
   ]
  },
  {
   "title": "All Time Uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes"
    }
   ]
  },
  {
   "title": "All Time Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_downloaded_bytes"
    }
   ]
  },
  {
   "title": "Cumulative Download/Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes",
     "legendFormat": "Download"
    },
    {
     "expr": "qbittorrent_global_upload_speed_bytes",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "All time uploaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Total Torrents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "qbittorrent_global_torrents" }
   ]
  },
  {
   "title": "Current Leechers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_leechers)"
    }
   ]
  },
  {
   "title": "Current Seeders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_seeders)"
    }
   ]
  },
  {
   "title": "States",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_torrent_states", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Leechers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_leechers)",
     "legendFormat": "Leechers"
    },
    {
     "expr": "sum(qbittorrent_torrent_seeders)",
     "legendFormat": "Seeders"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_upload_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Upload Torrents",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "(qbittorrent_torrent_upload_speed_bytes > 0) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed by Torrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_download_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 51 },
   "targets": [
    { "expr": "qbittorrent_global_categories", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 51 },
   "targets": [
    { "expr": "qbittorrent_global_tags", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Torrent Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "qbittorrent_torrent_ratio", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Ratio repartition",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(qbittorrent_torrent_ratio <= 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(qbittorrent_torrent_ratio > 1 and qbittorrent_torrent_ratio <= 2)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(qbittorrent_torrent_ratio > 2 and qbittorrent_torrent_ratio <= 5)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(qbittorrent_torrent_ratio > 5 and qbittorrent_torrent_ratio <= 10)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(qbittorrent_torrent_ratio > 10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracker Stats",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "qbittorrent_tracker_peers", "legendFormat": "{{url}}" },
    { "expr": "qbittorrent_tracker_seeders", "legendFormat": "{{url}}" },
    { "expr": "qbittorrent_tracker_leeches", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Trackers Status",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "qbittorrent_tracker_status", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Top 5 popularity",
   "type": "bargauge",
   "description": "ratio / time_active\n(time_active in month)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, qbittorrent_torrent_ratio / (qbittorrent_torrent_time_active / 2592000))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents Popularity",
   "type": "timeseries",
   "description": "ratio / time_active\n(time_active in month)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "qbittorrent_torrent_ratio / (qbittorrent_torrent_time_active / 2592000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 81 },
   "targets": [
    { "expr": "qbittorrent_torrent_ratio", "legendFormat": "__auto" },
    { "expr": "qbittorrent_torrent_added_on", "legendFormat": "__auto" },
    {
     "expr": "qbittorrent_torrent_total_uploaded_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "qbittorrent_torrent_size_bytes", "legendFormat": "__auto" },
    {
     "expr": "qbittorrent_torrent_ratio / (qbittorrent_torrent_time_active / 2592000)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}