{
 "title": "vnstat metrics",
 "description": "vnstat dashboard",
 "tags": [
  "vnstat",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vnstat_traffic_5min,instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(vnstat_traffic_5min{instance=~\"${instance}:.*\"},interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Network Traffic (5min)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vnstat_traffic_5min{instance=~\"${instance}:.*\", interface=~\"${interface}\"}[5m])",
     "legendFormat": "{{interface}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Monthly Network Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vnstat_traffic_monthly{instance=~\"${instance}:.*\", interface=~\"${interface}\", direction=\"rx\"}",
     "legendFormat": "RX Total"
    },
    {
     "expr": "vnstat_traffic_monthly{instance=~\"${instance}:.*\", interface=~\"${interface}\", direction=\"tx\"}",
     "legendFormat": "TX Total"
    }
   ]
  },
  {
   "title": "Traffic by Interface",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vnstat_traffic_daily{instance=~\"${instance}:.*\", interface=~\"${interface}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vnstat_traffic_hourly{instance=~\"${instance}:.*\", interface=~\"${interface}\"}[1h])/3600",
     "legendFormat": "{{interface}} - {{direction}}"
    }
   ]
  },
  {
   "title": "Daily Traffic Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vnstat_traffic_daily{instance=~\"${instance}:.*\", interface=~\"${interface}\"}[24h])/86400",
     "legendFormat": "{{interface}} - {{direction}}"
    }
   ]
  }
 ]
}