pipeline {
    agent {
      kubernetes {
        agentContainer 'jnlp'
        agentInjection true
        cloud 'comms'
        defaultContainer 'helm'
        inheritFrom 'helm'
        namespace 'monitoring'
        yamlFile 'nautobot/jenkins.yaml'
      }
    }
    environment {
      k_context='kubernetes-admin@comms'
      MY_KUBECONFIG='comms-kubeconfig'
    }
    stages {
        stage('Checkout') {
            steps {
                node(label='helm') {
                  withKubeConfig(caCertificate: '', clusterName: 'comms', contextName: "${env.k_context}", credentialsId: "${env.MY_KUBECONFIG}", namespace: 'monitoring', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.5.33:6443') {
                    echo("Checkout ${env.BRANCH_NAME} from GitHub. . .")
                    checkout scm
                  }
                }
            }
        }
        stage('Test') {
            steps {
                node(label='helm') {
                  withKubeConfig(caCertificate: '', clusterName: 'comms', contextName: "${env.k_context}", credentialsId: "${env.MY_KUBECONFIG}", namespace: 'monitoring', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.5.33:6443') {
                    ansiColor('xterm') {
                      echo 'Testing kubectl. . .'
                      echo("check for working kubectl")
                      sh("kubectl get all")
                    }
                  }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
