pipeline {
    agent {
      kubernetes {
        agentContainer 'jnlp'
        agentInjection true
        cloud 'the-hard-way'
        defaultContainer 'helm'
        inheritFrom 'helm'
        namespace 'jenkins'
      }
    }
    environment {
      k_context='kubernetes-admin@comms'
      MY_KUBECONFIG='comms-kubeconfig'
    }
    stages {
        stage('Checkout') {
            steps {
                node(label='helm') {
                  withKubeConfig(caCertificate: '', clusterName: 'comms', contextName: "${env.k_context}", credentialsId: "${env.MY_KUBECONFIG}", namespace: 'nautobot', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.5.33:6443') {
                    echo("Checkout ${env.BRANCH_NAME} from GitHub. . .")
                    checkout scm
                    echo("check for working kubectl")
                    sh("kubectl get all")
                  }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
