apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0
spec:
  storageClassName: csi-lvm-linear
  accessModes:
    - ReadWriteOnce
    - ReadWrtieMany
  resources:
    requests:
      storage: 97656250Ki
