apiVersion: v2
appVersion: 4.0.2
dependencies:
- alias: annotationAutodiscovery
  condition: annotationAutodiscovery.enabled
  name: feature-annotation-autodiscovery
  repository: ""
  version: 1.0.0
- alias: applicationObservability
  condition: applicationObservability.enabled
  name: feature-application-observability
  repository: ""
  version: 1.0.0
- alias: autoInstrumentation
  condition: autoInstrumentation.enabled
  name: feature-auto-instrumentation
  repository: ""
  version: 1.0.0
- alias: clusterEvents
  condition: clusterEvents.enabled
  name: feature-cluster-events
  repository: ""
  version: 1.0.0
- alias: clusterMetrics
  condition: clusterMetrics.enabled
  name: feature-cluster-metrics
  repository: ""
  version: 1.0.0
- alias: costMetrics
  condition: costMetrics.enabled
  name: feature-cost-metrics
  repository: ""
  version: 1.0.0
- alias: hostMetrics
  condition: hostMetrics.enabled
  name: feature-host-metrics
  repository: ""
  version: 1.0.0
- alias: integrations
  name: feature-integrations
  repository: ""
  version: 1.0.0
- alias: nodeLogs
  condition: nodeLogs.enabled
  name: feature-node-logs
  repository: ""
  version: 1.0.0
- alias: podLogsViaLoki
  condition: podLogsViaLoki.enabled
  name: feature-pod-logs-via-loki
  repository: ""
  version: 1.0.0
- alias: podLogsViaOpenTelemetry
  condition: podLogsViaOpenTelemetry.enabled
  name: feature-pod-logs-via-opentelemetry
  repository: ""
  version: 1.0.0
- alias: podLogsViaKubernetesApi
  condition: podLogsViaKubernetesApi.enabled
  name: feature-pod-logs-via-kubernetes-api
  repository: ""
  version: 1.0.0
- alias: podLogsObjects
  condition: podLogsObjects.enabled
  name: feature-pod-logs-objects
  repository: ""
  version: 1.0.0
- alias: profiling
  condition: profiling.enabled
  name: feature-profiling
  repository: ""
  version: 1.0.0
- alias: profilesReceiver
  condition: profilesReceiver.enabled
  name: feature-profiles-receiver
  repository: ""
  version: 1.0.0
- alias: prometheusOperatorObjects
  condition: prometheusOperatorObjects.enabled
  name: feature-prometheus-operator-objects
  repository: ""
  version: 1.0.0
- alias: telemetryServices
  name: telemetry-services
  repository: ""
  version: 1.0.0
- condition: alloy-operator.deploy
  name: alloy-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.5.3
description: Capture all telemetry data from your Kubernetes cluster.
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
- email: robert.lankford@grafana.com
  name: rlankfo
name: k8s-monitoring
sources:
- https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
type: application
version: 4.0.2
