{{- if and .Values.prometheus.enabled .Values.prometheus.ingress.enabled -}}
  {{- $pathType := .Values.prometheus.ingress.pathType | default "ImplementationSpecific" -}}
  {{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" -}}
  {{- $servicePort := .Values.prometheus.ingress.servicePort | default .Values.prometheus.service.port -}}
  {{- $routePrefix := list .Values.prometheus.prometheusSpec.routePrefix -}}
  {{- $paths := .Values.prometheus.ingress.paths | default $routePrefix -}}
  {{- $apiIsStable := eq (include "kube-prometheus-stack.ingress.isStable" .) "true" -}}
  {{- $ingressSupportsPathType := eq (include "kube-prometheus-stack.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "kube-prometheus-stack.ingress.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.prometheus.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .Values.prometheus.ingress.annotations) . | nindent 4 }}
{{- end }}
  name: {{ $serviceName }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{- if .Values.prometheus.ingress.labels }}
{{ toYaml .Values.prometheus.ingress.labels | indent 4 }}
{{- end }}
spec:
  {{- if $apiIsStable }}
  {{- if .Values.prometheus.ingress.ingressClassName }}
  ingressClassName: {{ .Values.prometheus.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
  rules:
    - host: prometheus.breeze-blocks.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    {{- end }}
  {{- if .Values.prometheus.ingress.tls }}
  tls:
    - secretName: prometheus-tls
      hosts:
        - prometheus.breeze-blocks.net
        - prometheus
        - prometheus.monitoring
        - prometheus.monitoring.comms.local
  {{ end }}
