name: label alloy operator updates
on:
  issues: {}
  pull_request:
    branches:
      - main
    paths:
      - "ao/**"
  workflow_dispatch: {}
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  ao:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: add labels
        uses: actions-ecosystem/action-add-labels@main
        with:
          github_token: ${{ secrets.PROJECT_PAT }}
          labels: ao
